//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Test_Group
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string Lab_Name { get; set; }
    
        public virtual Lab_Info Lab_Info { get; set; }
    }
}
