//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Normal_Value
    {
        public int ValueID { get; set; }
        public Nullable<int> SubTestID { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string Age_gender_cat { get; set; }
    
        public virtual Sub_Test Sub_Test { get; set; }
    }
}
